Use the following dataset - https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('/content/IMDB Dataset.csv', engine='python',error_bad_lines=False)

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


In [3]:
movies.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
movies['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

# Problem 1

## Apply all the preprocessing techniques that you think are necessary

In [7]:
# Lowercasing
movies['review'] = movies['review'].str.lower()

In [8]:
# Remove HTML Tags
import re
def remove_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'',text)

movies['review'] = movies['review'].apply(remove_tags)

In [9]:
movies['review'][1]

'a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [10]:
#Remove Punctuations
import string

def remove_punctuation(text):
  for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
  return text
  
movies['review'] = movies['review'].apply(remove_punctuation)

In [11]:
movies['review'][1]

'a wonderful little production the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done'

In [ ]:
# Sentence Tokenize and Removing stop words
from nltk.corpus import stopwords
from nltk import sent_tokenize, word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')
stop_words = stopwords.words('english')

def remove_stopwords(text):
  sentence = word_tokenize(text)
  new_text = []
  for word in sentence:
    if word not in stop_words:
      new_text.append(word)
  return new_text

In [13]:
remove_stopwords('Hello my name is jon snow and I am the king of north'.lower())

['hello', 'name', 'jon', 'snow', 'king', 'north']

In [14]:
movies['review'] = movies['review'].apply(lambda x:[item for item in x.split() if item not in stop_words]).apply(lambda x:" ".join(x))

In [15]:
movies['review'][1]

'wonderful little production filming technique unassuming oldtimebbc fashion gives comforting sometimes discomforting sense realism entire piece actors extremely well chosen michael sheen got polari voices pat truly see seamless editing guided references williams diary entries well worth watching terrificly written performed piece masterful production one great masters comedy life realism really comes home little things fantasy guard rather use traditional dream techniques remains solid disappears plays knowledge senses particularly scenes concerning orton halliwell sets particularly flat halliwells murals decorating every surface terribly well done'

In [16]:
movies

review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production filming technique ...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically theres family little boy jake thinks...  negative
4      petter matteis love time money visually stunni...  positive
...                                                  ...       ...
49995  thought movie right good job wasnt creative or...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  im going disagree previous comment side maltin...  negative
49999  one expects star trek movies high art fans exp...  negative

[50000 rows x 2 columns]

In [17]:
movies.isnull().sum()

review       0
sentiment    0
dtype: int64

In [18]:
X = movies.iloc[:,0:1]
y = movies['sentiment']

In [19]:
X

review
0      one reviewers mentioned watching 1 oz episode ...
1      wonderful little production filming technique ...
2      thought wonderful way spend time hot summer we...
3      basically theres family little boy jake thinks...
4      petter matteis love time money visually stunni...
...                                                  ...
49995  thought movie right good job wasnt creative or...
49996  bad plot bad dialogue bad acting idiotic direc...
49997  catholic taught parochial elementary schools n...
49998  im going disagree previous comment side maltin...
49999  one expects star trek movies high art fans exp...

[50000 rows x 1 columns]

In [20]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [21]:
y

array([1, 1, 1, ..., 0, 0, 0])

# Using Bag of words 

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state =48)

In [ ]:
X_train

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=4000)

In [ ]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.fit_transform(X_test['review']).toarray()

In [ ]:
X_train_bow.shape

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_bow, y_train)
y_pred = rf.predict(X_test_bow)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
gb.fit(X_train_bow, y_train)
y_pred = gb.predict(X_test_bow)
accuracy_score(y_test, y_pred)

# Using Tfdf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=20000)

X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.fit_transform(X_test['review']).toarray()

In [ ]:
X_train_tfidf.shape

In [ ]:
gb = GaussianNB()
gb.fit(X_train_tfidf, y_train)
y_pred = gb.predict(X_test_tfidf)
accuracy_score(y_test, y_pred)

In [37]:
rf = RandomForestClassifier()
rf.fit(X_train_tfidf, y_train)
y_pred = rf.predict(X_test_tfidf)

In [38]:
accuracy_score(y_test, y_pred)

0.5639

# Using Word2Vec

In [ ]:
import gensim
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords
from nltk import sent_tokenize, word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')

In [23]:
from nltk import sent_tokenize, word_tokenize

story = []
for doc in movies['review']:
  sentence = sent_tokenize(doc)
  for sent in sentence:
    story.append(simple_preprocess(sent))

In [24]:
model = gensim.models.Word2Vec(window=20,
                               min_count=2)
model.build_vocab(story)

In [26]:
model.corpus_count

50000

In [29]:
model.train(story, total_examples = model.corpus_count, epochs=model.epochs)

(27898002, 29560805)

In [31]:
len(model.wv.index2entity)

80889

In [40]:
model.wv.vectors[0]

array([ 1.5848184 ,  1.7862868 , -0.550234  , -1.4706271 , -1.1528329 ,
        2.4976475 , -0.95636356, -1.612448  ,  0.69130284, -1.5430642 ,
       -1.1484299 , -0.51443785,  0.52409977,  2.2522001 ,  0.8896623 ,
        1.6668141 ,  2.0329723 ,  4.1095686 ,  0.15750849,  1.9826334 ,
        1.5766363 , -2.8794582 ,  1.3160341 , -1.8223794 ,  1.8689117 ,
        2.2046685 , -1.8974521 ,  3.189433  ,  2.0111966 ,  4.465969  ,
        0.21234378,  1.4654472 ,  1.9565967 ,  0.82907027, -1.2982589 ,
        2.585345  , -0.7624835 ,  0.37933454,  0.6497519 , -3.846617  ,
       -2.4254398 , -4.6440334 ,  0.8331184 , -4.361848  ,  3.2391634 ,
       -1.6458031 , -2.298841  , -0.15492827, -0.7767921 ,  1.3081765 ,
       -0.04253916,  0.94930875,  1.0317225 , -2.2421596 , -1.1969212 ,
       -1.8050209 , -1.2199494 , -3.1914377 ,  0.32090044, -0.912492  ,
       -2.647805  ,  2.526351  ,  3.216273  ,  1.2691251 ,  0.1381923 ,
        1.7067189 ,  0.6787527 ,  0.6913773 , -2.6984818 ,  2.60

In [36]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index2entity]
    return np.mean(model.wv[doc], axis=0)

In [37]:
document_vector(movies['review'].values[0])

array([ 0.11309962,  0.27356952,  0.30278292, -0.2973716 , -0.37326473,
        0.24151625,  0.4798162 ,  0.18341163, -0.2575867 ,  0.24860676,
        0.91596335,  0.19843267,  0.36531228, -0.16743337,  0.461395  ,
        0.04243102,  0.42370155, -0.11083147,  0.00466661, -0.1558012 ,
       -0.32781577,  0.05200383,  0.8982934 , -0.33724624,  0.18697642,
        0.24166448,  0.65641856,  0.1084829 , -0.14594199, -0.4083146 ,
        0.03455671,  0.07470871, -0.4753025 ,  0.6473746 , -0.3230121 ,
       -0.09036844, -0.01979775,  0.35274208,  0.24399401,  0.01559333,
        0.03092022, -0.29366443, -0.16470726,  0.06865116,  0.1629097 ,
       -0.18510252, -0.11317103, -0.15993524, -0.15749267, -0.06904194,
        0.25335705,  0.23827834,  0.04968162,  0.01049579, -0.4535438 ,
       -0.4200192 ,  0.20776242,  0.10271688,  0.9234779 , -0.02177838,
        0.22002843, -0.2449269 ,  0.57359403,  0.02314997, -0.11970576,
        0.56560254,  0.41220734,  0.529724  ,  0.18164621,  0.63

In [41]:
from tqdm import tqdm


In [43]:
X = []
for doc in tqdm(movies['review'].values):
    X.append(document_vector(doc))

100%|██████████| 50000/50000 [22:24<00:00, 37.18it/s]


In [45]:
X = np.array(X)
X[0]

array([ 0.11309962,  0.27356952,  0.30278292, -0.2973716 , -0.37326473,
        0.24151625,  0.4798162 ,  0.18341163, -0.2575867 ,  0.24860676,
        0.91596335,  0.19843267,  0.36531228, -0.16743337,  0.461395  ,
        0.04243102,  0.42370155, -0.11083147,  0.00466661, -0.1558012 ,
       -0.32781577,  0.05200383,  0.8982934 , -0.33724624,  0.18697642,
        0.24166448,  0.65641856,  0.1084829 , -0.14594199, -0.4083146 ,
        0.03455671,  0.07470871, -0.4753025 ,  0.6473746 , -0.3230121 ,
       -0.09036844, -0.01979775,  0.35274208,  0.24399401,  0.01559333,
        0.03092022, -0.29366443, -0.16470726,  0.06865116,  0.1629097 ,
       -0.18510252, -0.11317103, -0.15993524, -0.15749267, -0.06904194,
        0.25335705,  0.23827834,  0.04968162,  0.01049579, -0.4535438 ,
       -0.4200192 ,  0.20776242,  0.10271688,  0.9234779 , -0.02177838,
        0.22002843, -0.2449269 ,  0.57359403,  0.02314997, -0.11970576,
        0.56560254,  0.41220734,  0.529724  ,  0.18164621,  0.63

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


In [48]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.8502

In [49]:
X_test[0]

array([ 0.55153376,  0.72414786,  0.18592636, -0.0054199 , -0.18095218,
        0.2749217 , -0.03656687,  0.14305946, -0.26579192, -0.17228258,
        0.42171553, -0.12366886,  0.41687357,  0.14109486,  0.32677856,
       -0.18901446, -0.00519055, -0.22451928, -0.4066445 ,  0.2020016 ,
       -0.02204471, -0.01830081,  0.5785096 , -0.1063636 , -0.2290858 ,
        0.13080399,  0.11949017,  0.22083999,  0.15507042, -0.6756861 ,
       -0.04954484,  0.0186647 , -0.34792188,  0.1701547 , -0.0048723 ,
       -0.4386901 , -0.26054665,  0.1262883 ,  0.2785134 , -0.33681363,
       -0.11680575, -0.31260338, -0.6945613 ,  0.30966255,  0.25012308,
        0.13202314,  0.04400609, -0.00967083,  0.10673098,  0.23692045,
        0.34077698,  0.20711029,  0.06474486, -0.35069796,  0.08670037,
       -0.06728145, -0.16909152, -0.22081678,  0.6035484 ,  0.16449788,
       -0.03323462, -0.5552389 ,  0.7988134 ,  0.3867848 , -0.15454987,
        0.5992045 ,  0.18243578,  0.02719962,  0.22942787,  0.10