In [1]:
import numpy as np
import pandas as pd

In [2]:
# BAG of Words
data = {
    'text':['How are you', 'How did you come', 'Where did you live', 'How did you did'],
    'output':[0,1,1,0]
}
my_df = pd.DataFrame(data)

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bag_of_words = cv.fit_transform(my_df['text'])

In [4]:
bag_of_words

<4x7 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [5]:
print(cv.vocabulary_)

{'how': 3, 'are': 0, 'you': 6, 'did': 2, 'come': 1, 'where': 5, 'live': 4}


In [6]:
bag_of_words.toarray()

array([[1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 1],
       [0, 0, 2, 1, 0, 0, 1]])

In [7]:
# for unknown word
cv.transform(['How did you come and live']).toarray()

array([[0, 1, 1, 1, 1, 0, 1]])

In [8]:
# Bi-gram
cv = CountVectorizer(ngram_range=(2,2))
bow_bigram = cv.fit_transform(my_df['text'])
print(cv.vocabulary_)
bag_of_words.toarray()

{'how are': 2, 'are you': 0, 'how did': 3, 'did you': 1, 'you come': 5, 'where did': 4, 'you live': 7, 'you did': 6}


array([[1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 1],
       [0, 0, 2, 1, 0, 0, 1]])

In [9]:
# tri-gram
cv = CountVectorizer(ngram_range=(3,3))
bow_bigram = cv.fit_transform(my_df['text'])
print(cv.vocabulary_)
bag_of_words.toarray()

{'how are you': 3, 'how did you': 4, 'did you come': 0, 'where did you': 5, 'did you live': 2, 'did you did': 1}


array([[1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 1],
       [0, 0, 2, 1, 0, 0, 1]])

In [10]:
# uni, bi and tri-gram
cv = CountVectorizer(ngram_range=(1,3))
bow_bigram = cv.fit_transform(my_df['text'])
print(cv.vocabulary_)
bag_of_words.toarray()

{'how': 8, 'are': 0, 'you': 17, 'how are': 9, 'are you': 1, 'how are you': 10, 'did': 3, 'come': 2, 'how did': 11, 'did you': 4, 'you come': 18, 'how did you': 12, 'did you come': 5, 'where': 14, 'live': 13, 'where did': 15, 'you live': 20, 'where did you': 16, 'did you live': 7, 'you did': 19, 'did you did': 6}


array([[1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1, 1],
       [0, 0, 2, 1, 0, 0, 1]])

In [14]:
# Tf-Idf
# data = {
#     'text':['How are you', 'How did you come', 'Where did you live', 'How did you did'],
#     'output':[0,1,1,0]
# }
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(my_df['text']).toarray()

array([[0.77157901, 0.        , 0.        , 0.49248889, 0.        ,
        0.        , 0.40264194],
       [0.        , 0.69218835, 0.44181486, 0.44181486, 0.        ,
        0.        , 0.3612126 ],
       [0.        , 0.        , 0.38991559, 0.        , 0.61087812,
        0.61087812, 0.31878155],
       [0.        , 0.        , 0.84003859, 0.4200193 , 0.        ,
        0.        , 0.3433933 ]])

In [18]:
tfidf.idf_

array([1.91629073, 1.91629073, 1.22314355, 1.22314355, 1.91629073,
       1.91629073, 1.        ])